Hosung99/FT_IRC

Client.cpp, Client.hpp, Server.cpp
- Client Class 구현
- Client.hpp 추가
- User명령어에 사용되는 필드값들 추가(hostname, servername, realname) 
- Client.cpp 추가
- 생성자, getter setter 함수들 추가
- close #2
=> [Feature] Client class 구현

.gitignore
=> [init] .gitignore 생성

Command.cpp, Command.hpp, Makefile, Server.cpp, Server.hpp, main.hpp
- Channel 파일, Command 파일 생성
- 
- Command객체에서 command를 실행하도록 합니다.
-
=> [init] : Command,Channel파일 생성

Command.cpp, Command.hpp, Server.cpp, Server.hpp
-command 에서 server 를 가지도록 수정
- Server 에서 command 를 생성할때 server 를 가지도록 수정
- Command 함수들 인자값으로 사용하던 부분들을 서버에서 가져오도록 수정
- close #11
=> [Refactor] command 에서 server를 가지도록 수정

Command.cpp, Command.hpp, Server.cpp
- ping pong 명령어 추가
- ping 함수 추가 (서버에서 ping 명령어를 받으면 pong 을 보내주기 때문에 ping 에서 pong 작업까지 진행)
- nick validation 검사에서 isspecial 부분의 !를 제거 -> 논리상으로는 ! 가 있는게 맞는거같은데 저부분에서 계속 validation이 걸림
- close #18
=> [Feature] ping pong 명령어 추가

Command.cpp, Server.cpp
- 클라이언트에서 인증 중 ctrl + c 입력시 세그멘테이션 발생하던 오류 해결
-  client find시 fds[i].fd로 찾도록
-  USER인증 완료 후 client쪽으로 접속됐다고 알림
- client find시 해당 fd로 찾도록 해결
=> fix : 클라이언트 종료시 오류

Channel.cpp, Channel.hpp
- Channel 클래스 구현
- Channel.cpp, Channel.hpp 구현
- close #9
=> [Feature] channel 클래스 구현

Client.hpp, Command.cpp
- 이미 인증된 상태에서 PASS,USER,NICK칠 시 에러
- USER에서 realname :뒤 다 들어가도록
- USER에서 realname은 :뒤에 다 들어가도록 (공백포함)
- run에서 else문에 명령어들 추가
=> feat : realname파싱

Client.cpp, Client.hpp, Server.cpp, Server.hpp
- Server 와 Client 에서 ChannelList 정보 추가
- Server.cpp, hpp 에 channelList 필드 추가 및 관련 함수 추가
- Client.cpp, hpp 에 Client 가 참여한 channelList 필드 추가 및 관련 함수 추가
=> [Feature] ChannelList를 Server 와 Client에 추가

Server.cpp, Server.hpp
- Server channelList return 값 수정
- Server channelList return 값 map<string, client> 에서 map<string, channel> 로 수정
=> [Fix] Server channelList return 값 수정

Channel.cpp, Channel.hpp, Command.cpp, Command.hpp, Makefile, Server.cpp, Server.hpp, main.hpp
- PRIVMSG 함수
- QUIT 함수
- channel,server객체에 channel찾는 함수들 추가
- PRIVMSG함수 완료
- QUIT함수 완료
=> feat : PRIVMSG,QUIT명령어

Command.cpp, Command.hpp, Makefile, Server.cpp, Server.hpp, Util.cpp, Util.hpp, main.hpp
- Join 함수 구현
- Util.cpp 추가 : split 함수 구현
- Server 클래스에 appendnewChannel 함수 추가
- Command 에 join 함수 추가 채널에 모든 메시지를 보내는 msgToAllChannel 추가
- close #25
=> [Feature] Join 함수 만들기

Command.cpp, Command.hpp, main.hpp
=> feat : PART 명령어

Command.cpp, Command.hpp
- nameListMsg 함수 구현
- nameListMsg : join 할시에 해당 방에 있는 Client들의 리스트를 출력하는 함수
=> [Feature] nameListMsg 함수 구현

Command.cpp, Command.hpp, main.hpp
- KICK 명령어 완성
- KICK 명령어 완성
- PART시 화면 나가지도록
=> feat : KICK 명령어

Bot.cpp, Bot.hpp, Channel.cpp, Channel.hpp, Client.cpp, Client.hpp, Command.cpp, Command.hpp, Makefile, Server.cpp, Server.hpp
- BOT 객체 추가
- BOT명령어 추가
- client쪽 함수들 카멜케이스화
- Bot.cpp, Bot.hpp파일 생성
- 모든 채널마다 갖고있고, Server의 Client리스트의 -1로 Bot_client가 들어있다.
=> feat : BOT명령어 추가

Channel.cpp, Channel.hpp, Command.cpp, Command.hpp, main.hpp
- Mode 명령어 구현
- Channel.cpp, hpp -> channel이 하나의 operator을 가지고 있을 수 있던 부분을 vector로 여러 fd 를 가지도록 수정
- Command.cpp, hpp -> Mode 함수 추가
-  Mode 에는 i, k, l, o, t 옵션을 넣어주었다.
- checkMode 함수로 해당 channel에 해당 모드가 적용 되어있는지 확인할 수 있다. ex) checkMode(INVITE);
- close #33
=> [Feature] mode 명령어 구현

Bot.cpp, Channel.cpp, Channel.hpp, Command.cpp, Command.hpp, main.hpp
- TOPIC명령어 추가
- TOPIC 명령어 추가
- join시에 topicMsg명령어를 클라이언트로 전송함
=> feat : TOPIC 명령어 추가

Client.cpp, Client.hpp, Command.cpp
- irssi에서 닉네임중복시에 _를 붙이도록 수정
- irssi에서 중복답변을 받으면 nick을 _로 다시보내서 이에 대한 처리를 했습니다.
=> fix : 닉네임중복 수정

Channel.cpp, Channel.hpp, Command.cpp, Command.hpp, main.hpp
- Join 함수 Invite 와 Key 에 대한 검증 하도록 수정
- Invite 함수 구현
- /join <채널명, ...> <키값, ...> 처리할 수 있게 인자 추가
- join 의 인자 갯수가 3개 이상이면 key 값도 확인함
- 채널에서 checkMode 함수로 Invite 모드인지 Key 모드인지 체크
> Invite 모드일 경우 channel 에 inviteFd에 포함 되어있으면 join 허용
> Key 모드일 경우 인자로 받은 key 값이 channel의 key값과 동일하면 join 허용
- invite 함수 구현 : /invite < nickname > < channel >
- 해당 유저를 channel invite list 에 추가하고, 초대했다는 메시지를 보냄
- close #37
=> [Feature] Channel Mode에 따른 join 검증 로직 추가, invite 함수 구현

Command.cpp, Server.cpp
- part명령어 실행 시 operator권한도 삭제
- part명령어 실행시 removeOperator함수로 해당 fd의 권한을 삭제함
=> fix : part시 operator권한도 삭제

Command.cpp
- 파일전송 /dcc send username ./Desktop/a.txt
- 파일받기 /dcc get userfromname
- privmsg에서 파싱으로 :는 안붙도록 수정
=> feat : 파일전송 가능

Makefile
- Makefile fsanitize 옵션 관련 문제 추가
=> docs: Makefile fsanitize 옵션 관련 문제 추가

Command.cpp
- 클라이언트를 지워야하는 상황에서 delete안하도록 변경
- 클라이어트를 지워야할 때 delete안하고 erase만하도록 변경
=> fix : delete안하고 erase만

Command.cpp, Makefile, Server.cpp, Server.hpp
- 인증이 안된 상태에서 다른 명령어 실행시 abort발생 에러 해결
- 인증이 안된 상태에서 다른 명령어 실행시 abort발생 에러 해결
=> fix : 인증안하고 다른 명령어 실행시 에러

Command.cpp
- 없는채널에서 kick시 abort 수정
- 채널이 있는지 체크를 하고 kick하도록 수정
=> fix : 없는 채널에서 kick시 abort

Channel.cpp, Command.cpp, main.hpp
- mode 명령어 입력값 조건 추가
- Limit 모드 걸려있는 channel join 처리 추가
- mode 명령어 입력 시 +++---++ 와 같이 sign이 이어질때 처리 추가
- mode 명령어 입력 시 여러 인자를 추가로 요구하는 경우에 대한 처리 추가 (ex : mode +ilk 20 abc)
- 중복된 모드 옵션에 대한 메시지 제거
- Limit 옵션 걸린 채널에 join 할때 제약 추가
=> [Feature] mode 명령어 입력값 조건 추가

srcs/commands/Join.cpp
=> [Feature] join 할때 이미 들어가 있으면 continue 조건 추가

includes/Client.hpp, srcs/Client.cpp, srcs/Command.cpp, srcs/Server.cpp, srcs/commands/Nick.cpp, srcs/commands/Pass.cpp, srcs/commands/Quit.cpp, srcs/commands/User.cpp
- fix: quit을 하는 경우 clearClient() 하도록 수정
=> fix: quit을 하는 경우 clearClient() 하도록 수정

srcs/Channel.cpp, srcs/Client.cpp, srcs/Server.cpp, srcs/commands/Join.cpp, srcs/commands/Quit.cpp
- quit후 재접속 시 말이 두번 나오던 부분 수정
- quit후 재접속 시 말이 두번 나오던 부분 수정
=> fix : quit후 재접속시 말 두개 나오던거

Makefile, includes/Command.hpp, includes/Error.hpp, includes/Server.hpp, includes/Util.hpp, main.hpp, srcs/Channel.cpp, srcs/Error.cpp, srcs/Util.cpp, srcs/commands/Invite.cpp, srcs/commands/Join.cpp, srcs/commands/Kick.cpp, srcs/commands/Mode.cpp, srcs/commands/Nick.cpp, srcs/commands/Part.cpp, srcs/commands/Pass.cpp, srcs/commands/Ping.cpp, srcs/commands/Privmsg.cpp, srcs/commands/Topic.cpp, srcs/commands/User.cpp
nickname 중복 검사 대소문자 구분 없이 하도록 수정
- error 메시지 전용 파일 추가, 기존 에러메시지  수정
- 에러 메시지 형식을 가지고있는 Error.cpp, hpp 추가
- 기존 error 메시지 수정
- limit 제한을 봇을 고려하도록 수정
- kick을 봇에게 못하도록 수정
- isSepcial Util.hpp 에 추가
=> [Refactor] error 메시지 함수 추가, 기존코드  수정

main.cpp, srcs/Command.cpp, srcs/Server.cpp, srcs/commands/Pass.cpp, srcs/commands/Quit.cpp
- double free & not allocated memory free 문제 해결 중
- client *미리 delete 후 null 대입 후 erase 진행
=> fix: memory leak 관련부분 고치는 중

includes/Command.hpp, includes/Error.hpp, includes/Server.hpp, srcs/Client.cpp, srcs/Command.cpp, srcs/Error.cpp, srcs/Server.cpp, srcs/Util.cpp, srcs/commands/Invite.cpp, srcs/commands/Join.cpp, srcs/commands/Kick.cpp, srcs/commands/Mode.cpp, srcs/commands/Nick.cpp, srcs/commands/Part.cpp, srcs/commands/Pass.cpp, srcs/commands/Ping.cpp, srcs/commands/Privmsg.cpp, srcs/commands/Quit.cpp, srcs/commands/Topic.cpp, srcs/commands/User.cpp
- 동적 메모리 할당 최소화
- client 객체 저장할 때, 정적 메모리로 저장하므로써, 메모리 릭에 관련된 부분 최소화 및 map에 대한 모든 list들 reference 변수화 함
=> refactor: Client * 대신 Client 객체 자체를 map에 저장하므로써 동적 메모리 할당 최소화
